
#include <giga-engine.h>

int COLOR_RGB = 0;
int COLOR_RGBA = 0;
int COLOR_RGB16F = 0;
int COLOR_RED = 0;
int COLOR_RED16F = 0;
int COLOR_DEPTH_COMPONENT32 = 0;
int COLOR_DEPTH_COMPONENT = 0;

int FRAMEBUFFER_SLOT_0 = 0;
int FRAMEBUFFER_SLOT_1 = 0;
int FRAMEBUFFER_SLOT_2 = 0;
int FRAMEBUFFER_SLOT_3 = 0;
int FRAMEBUFFER_SLOT_4 = 0;
int FRAMEBUFFER_SLOT_5 = 0;
int FRAMEBUFFER_SLOT_DEPTH = 0;
